# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e62898d41f3a47f657f700e0ac6a5a615df020debff8cf88aa058bf77ae4748a81cd35caa86618c0f077ff415250caac0000220a29f85555d71d8ae0f55d884

test:
  secret_key_base: cc94d4ec1bcd33cec454b14fc13a3418a03b15eb99fed3f24d9c061864e3e39fa51eb284953d3f098d0fc20bc468a4f8bf23f012a1450b6da46e9775a5ed03cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
